stages:
  - install-rke

rke:
  stage: install-rke
  tags:
    - Local-Runner
  script:
    - mkdir /home/gitlab-runner/rke
    - cp -rf * /home/gitlab-runner/rke
    - cd /home/gitlab-runner/rke
    - ansible-playbook rke-user.yml && ansible-playbook rke-module.yml
    - ansible-playbook rke-disabled-swap.yml && ansible-playbook add-user.yml
    - rke up
    - mkdir -p $HOME/.kube
    - cp -i /home/gitlab-runner/rke/kube_config_cluster.yml ~/.kube/config
    - chown $(id -u):$(id -g) $HOME/.kube/config
    - kubectl get nodes


    # - docker stop $(docker ps -aq)
    # - docker system prune -f
    # - docker volume rm $(docker volume ls -q)
    # - docker image rm $(docker image ls -q)
    # - rm -rf /etc/ceph \
    #       /etc/cni \
    #       /etc/kubernetes \
    #       /opt/cni \
    #       /opt/rke \
    #       /run/secrets/kubernetes.io \
    #       /run/calico \
    #       /run/flannel \
    #       /var/lib/calico \
    #       /var/lib/etcd \
    #       /var/lib/cni \
    #       /var/lib/kubelet \
    #       /var/lib/rancher/rke/log \
    #       /var/log/containers \
    #       /var/log/pods \
    #       /var/run/calico
